### ISSUE TITLE
Compatibility issue free-ruler 2.0.5 MacOS Big Sur (11.2.3)

### ISSUE THREAD

**Issue by Beenhakker** [pascalpp/FreeRuler#102]
Hi,

Thanks for this great app. I have been using it for a long time.

I tried to open it today, and I get this error:

<img width="259" alt="Screenshot 2021-04-15 at 10 23 49" src="https://user-images.githubusercontent.com/8101319/114838200-c04f9280-9dd4-11eb-8de2-b377bcec2a15.png">

I installed it via Homebrew. I have seen a similar issue in the past.

**Comment by pascalpp** [comment]
Hmm I didn't realize this was available via homebrew. I'll have to look into that. In the meantime, please download from the releases page. https://github.com/pascalpp/FreeRuler/releases
