### ISSUE TITLE
Signing issues with non-App Store release

### ISSUE THREAD

**Issue by pascalpp** [pascalpp/FreeRuler#116]
I updated my dev/distribution certs in order to release #115 but I'm still told that the app "can’t be opened because Apple cannot check it for malicious software." so I'm forced to use the right-click > Open workaround. Not sure what exactly I need to do to fix this. Any guidance appreciated.

**Comment by jeff-h** [comment]
Hey, signing issues are the worst :( Not sure if you're aware but you do get two "[Technical Support Incidents](https://developer.apple.com/support/technical/)" per year included in your developer membership. I used one of mine last year specifically for some signing issues & questions I had, and they were happy enough to (try to) help.

**Comment by pascalpp** [comment]
Should be fixed now: https://github.com/pascalpp/FreeRuler/releases/tag/v2.0.7
