### ISSUE TITLE
Difficult to install on Ventura

### ISSUE THREAD

**Issue by RandomEngy** [pascalpp/FreeRuler#117]
Installing 2.0.6 on Ventura 13.3.1, M1 Pro.

The version from https://github.com/pascalpp/FreeRuler/releases had this error (signing I think?):
<img width="258" alt="image" src="https://github.com/pascalpp/FreeRuler/assets/9450861/4ec4e4cb-5b78-4283-8505-e473716d1861">

The app store had a different error when trying to install.

Finally got it to work by trying right-click -> Open multiple times on the one from the GitHub page.

**Comment by Libroru** [comment]
Same issue here please fix

**Comment by pascalpp** [comment]
This should be resolved in v2.0.7. https://github.com/pascalpp/FreeRuler/releases/tag/v2.0.7
