### ISSUE TITLE
Just to say thanks

### ISSUE THREAD

**Issue by val-hall** [pascalpp/FreeRuler#118]
Been using this since v1. 

Does exactly what I need - let me get pixel measurements of onscreen items.

I usually use it for messing about with HTML. No changes or improvements needed for me.

Just wanted to say that you've been updating it for free all along, and I really appreciate it.

THANKS!!!

**Comment by pascalpp** [comment]
Thanks for the kind words! Closing this ticket as completed 😛

**Comment by jeff-h** [comment]
I agree! Apple should just ship it with macOS already 😁
