### ISSUE TITLE
Can't install on Sonoma

### ISSUE THREAD

**Issue by Parakeet709** [pascalpp/FreeRuler#120]
[ Related to #117 ] I'm pretty sure the App Store version is fine, but the Github version won't work. "Apple can't run this app because it can not be scanned for malware" or something like that. Can you guys update it here so users can use it?
Edit: Got it to open on Sonoma

**Comment by pascalpp** [comment]
By the way this should be resolved for the non-app-store version in 2.0.7 https://github.com/pascalpp/FreeRuler/releases/tag/v2.0.7
