### ISSUE TITLE
Integrate UserDefaults system

### ISSUE THREAD

**Issue by pascalpp** [pascalpp/FreeRuler#16]
- ruler color
- active transparency
- inactive transparency
- float above other windows

**Comment by pascalpp** [comment]
Before adding the prefs window, need to figure out a pattern for saving various preferences.
Looking at https://github.com/radex/SwiftyUserDefaults or https://github.com/sindresorhus/Defaults

**Comment by pascalpp** [comment]
Looks like I need to learn about `Codable` and maybe `NSCoding`

**Comment by pascalpp** [comment]
Swift Package Manager Tutorial: https://www.raywenderlich.com/750-an-introduction-to-the-swift-package-manager

Carthage: https://github.com/Carthage/Carthage#differences-between-carthage-and-cocoapods

Differences between Carthage and CocoaPods: https://github.com/Carthage/Carthage#differences-between-carthage-and-cocoapods

**Comment by jeff-h** [comment]
Out of those I'd suggest you start with Carthage. That said, in an app this small I'm not sure you would really need anything additional for setting & accessing user preferences?

**Comment by pascalpp** [comment]
Yeah I've got SwiftyUserDefaults integrated using Carthage in this PR https://github.com/pascalpp/FreeRuler/pull/25

I'm planning to create a Ruler class (or struct?) which will be Codable so we can save each ruler in settings. That way we can persist the size, position, and units of each ruler separately. 

This is mostly out of curiosity rather than a pressing end user need, but I'm toying with the idea of creating a 'RulerSet' class so folks could make multiple sets of Rulers and persist them as an array in settings. But going to defer on that for now and focus on the other stuff in the 2.0 milestone.

**Comment by pascalpp** [comment]
Closed in #25
