### ISSUE TITLE
App icon

### ISSUE THREAD

**Issue by pascalpp** [pascalpp/FreeRuler#17]

**Comment by pascalpp** [comment]
this is pretty nifty: I added a special method to the AppDelegate to draw a window framed by rulers:

![image](https://user-images.githubusercontent.com/1355312/57201047-7069bf00-6f61-11e9-84eb-5e8ba4f20f64.png)

Thinking I can add some sort of 'Free Ruler' text to the window content and then do some manipulation in an image editor to rotate and skew it so it matches the conventional icon style, a la the Notes app:

![image](https://user-images.githubusercontent.com/1355312/57201067-a7d86b80-6f61-11e9-9d0a-1278462dfdb8.png)

**Comment by jeff-h** [comment]
Sounds very cool :)

**Comment by pascalpp** [comment]
Another idea I had: make an 'F' with the rulers:

![image](https://user-images.githubusercontent.com/1355312/57201839-2f2adc80-6f6c-11e9-8f34-d3d66d83c750.png)

If I do this I think I might make the window larger and put the rulers inside it. But I also don't want to give folks the impression that you can make more than 2 rulers. (I'm contemplating doing that but don't want to commit to it yet.)

**Comment by pascalpp** [comment]
![image](https://user-images.githubusercontent.com/1355312/57202086-2091f480-6f6f-11e9-95cf-5f7eea3f3d13.png)

**Comment by pascalpp** [comment]
![image](https://user-images.githubusercontent.com/1355312/57202862-3e178c00-6f78-11e9-9619-6695f1dd1797.png)

**Comment by pascalpp** [comment]
![image](https://user-images.githubusercontent.com/1355312/57203579-6060d800-6f7f-11e9-9d2f-7a0b27d06017.png)

**Comment by pascalpp** [comment]
![image](https://user-images.githubusercontent.com/1355312/57205782-f4866b80-6f8e-11e9-949f-7b4d62d18be5.png)

**Comment by pascalpp** [comment]
Updated the App Icon Helper scheme to render a custom ruler layout in a transparent window, so to generate the icon all we need to do is add the dropshadow and render different sizes. (Still need to update that fake window to look more like a real window. work in progress)

![image](https://user-images.githubusercontent.com/1355312/57742222-4b2a2e80-768e-11e9-9acd-0b6c78675fdf.png)

**Comment by pascalpp** [comment]
![Free Ruler Icon 1024](https://user-images.githubusercontent.com/1355312/57749220-2c866080-76ab-11e9-9140-6c6191dee118.png)

**Comment by pascalpp** [comment]
![icon_512x512](https://user-images.githubusercontent.com/1355312/57776614-f8805f00-76ed-11e9-947d-8a4a1a79443c.png)

**Comment by jeff-h** [comment]
Looks great!
