### ISSUE TITLE
remember window positions

### ISSUE THREAD

**Issue by pascalpp** [pascalpp/FreeRuler#5]

**Comment by jeff-h** [comment]
Strange; mine already does. Perhaps try putting an id in the window's `autosave name` field in IB? 

Select `RulerHorizontalWindow.xib` then in IB, select the window:

<img width="358" alt="Screen Shot 2019-04-16 at 8 52 40 PM" src="https://user-images.githubusercontent.com/841871/56195720-99e1aa00-6089-11e9-9166-4285bcd94d7f.png">

Then in the attributes tab:

<img width="291" alt="Screen Shot 2019-04-16 at 8 51 15 PM" src="https://user-images.githubusercontent.com/841871/56195642-774f9100-6089-11e9-9b89-6dc1465e4a70.png">

**Comment by jeff-h** [comment]
This works perfectly for me. However I suppose that's not saying a lot since it worked fine previously also :)
