### ISSUE TITLE
Is FreeRuler 2.0 coming any time soon?

### ISSUE THREAD

**Issue by rudifa** [pascalpp/FreeRuler#55]
Now that MacOS Catalina is upon us, the old 32-bit 1.7b5 app does not work any more.
In the meantime, I made a local build for myself.
Could I help in any way to speed up the release 2.0?

**Comment by pascalpp** [comment]
Hey cool. Yeah I'm trying to get a release out. But at the moment I'm struggling to get the cursor interaction working correctly.

I'm also still trying to decide if I should put it on the App Store or just do the direct download thing. I need to a do a bit more polish, updating the about box, etc.

If you have any experience with the cursor APIs, or just general feedback on the current state of the app, I'd be glad to hear it.

**Comment by jeff-h** [comment]
I also compiled it for myself yesterday lol. Can't live even a day without this, it seems :D Would you consider compiling it as a beta and distributing via Github releases just for the time being? It works more than well enough to be useful in its current state IMO.

Sorry I can't help re the cursor API. Sounds like you probably already know more about it than most!

**Comment by pascalpp** [comment]
https://github.com/pascalpp/FreeRuler/releases

**Comment by jeff-h** [comment]
Congratulations!

**Comment by rudifa** [comment]
I am away from my Mac keyboard until Monday evening.

In the meantime, thank you, Pascal, and congratulations!

Rudi
