### ISSUE TITLE
App store distribution

### ISSUE THREAD

**Issue by pascalpp** [pascalpp/FreeRuler#61]

**Comment by pascalpp** [comment]
Hmm. They don't like the name 'Free Ruler'. 
![image](https://user-images.githubusercontent.com/1355312/66694512-4d66d800-ec82-11e9-8b40-7ebb4e90dd92.png)

I've appealed, but not hopeful they're going to let that slide.

**Comment by jeff-h** [comment]
🙄

**Comment by pascalpp** [comment]
Maybe the App Store version could have a different name:

- Freedom Ruler
- Freedom Isn’t Free Ruler
- Free Hong Kong Ruler

Other ideas?

**Comment by pascalpp** [comment]
hey hey I appealed that I've been using that name since 2002 and that it's not just about the price but the ethos of the app or some happy horseshit and they changed their mind. https://apps.apple.com/us/app/free-ruler/id1483172210

**Comment by jeff-h** [comment]
Have to say, like you, I didn't expect that outcome! Great news, not just for the app but for my perception of Apple.
