### ISSUE TITLE
Add support for other units (inches, picas, cm)

### ISSUE THREAD

**Issue by pascalpp** [pascalpp/FreeRuler#68]

**Comment by vtstone** [comment]
Just checking in on to see if the ruler will be support the other units? Really enjoy this ruler

**Comment by duetosymmetry** [comment]
+1 for units

**Comment by fabulousrice** [comment]
I came here to upvote this. Metric and imperial distances please! Thanks

**Comment by rqqb** [comment]
+1 for units please.

**Comment by pascalpp** [comment]
This is now available in https://github.com/pascalpp/FreeRuler/releases/tag/v2.0.4
