### ISSUE TITLE
Ticks joined on non-retina

### ISSUE THREAD

**Issue by jeff-h** [pascalpp/FreeRuler#7]
On a non-retina display, the ticks which are drawn at every second pixel are actually joined. I am unsure why, but wondering if instead of pixels 2, 4, 6 etc they should be draw at 2.5, 4.5, 6.5 etc

**Comment by pascalpp** [comment]
I have a non-retina 27inch Thunderbolt Display and I don’t think this is happening for me. Can you post a screenshot?

**Comment by pascalpp** [comment]
Oh wait I am seeing that. Screenshot:
![image](https://user-images.githubusercontent.com/1355312/57181612-251db680-6e64-11e9-993b-b14e225245b0.png)
