### ISSUE TITLE
Cursor pixel position is only displays upper half

### ISSUE THREAD

**Issue by joostdekeijzer** [pascalpp/FreeRuler#74]
Great tool, thnx for the recent 64bit update!

A small bug: you only see the upper part of the horizontal "164" and vertical "109"

See attached image

<img width="414" alt="cursor value half" src="https://user-images.githubusercontent.com/216672/67470760-93427980-f64e-11e9-8a32-6ce5d335dba6.png">

**Comment by pascalpp** [comment]
@joostdekeijzer Thanks for the report. Can you also post a screenshot of your About this Mac window and your About Free Ruler window so I know what versions you're running?

**Comment by pascalpp** [comment]
like these:
![image](https://user-images.githubusercontent.com/1355312/67497132-883a1a00-f64b-11e9-82a5-a114d1904300.png)
![image](https://user-images.githubusercontent.com/1355312/67497164-99832680-f64b-11e9-8bc0-514f260f83cf.png)

**Comment by pascalpp** [comment]
Oh ha I'm seeing the bug locally on my machine now, not sure how that happened. Will fix.

**Comment by joostdekeijzer** [comment]
Hi Pascal,

I'm running the same version of Free Ruler on exactly the same machine you have :-) (well: more ram here...)
