### ISSUE TITLE
Implement help

### ISSUE THREAD

**Issue by pascalpp** [pascalpp/FreeRuler#76]
App Store rejection for 2.0.3:
![2789BD71-BC3D-4FB8-8E6A-0C4CEE4F015A](https://user-images.githubusercontent.com/1355312/67621763-11cf2080-f7e1-11e9-9d2a-90699c0671b9.png)

**Comment by jeff-h** [comment]
🙄

**Comment by pascalpp** [comment]
http://swiftrien.blogspot.com/2015/06/adding-apple-help-to-os-x-application.html

**Comment by pascalpp** [comment]
ended up using this guide https://marioaguzman.wordpress.com/2020/09/12/auth/
