### ISSUE TITLE
The labels indicating the reading of the mouse position are cut off

### ISSUE THREAD

**Issue by GVisconti84** [pascalpp/FreeRuler#78]
![Schermata 2019-11-05 alle 15 35 41](https://user-images.githubusercontent.com/201150/68217340-ba039700-ffe2-11e9-8c69-8295097cfbab.png)

**Comment by pascalpp** [comment]
This is fixed in v2.0.3 which you can download from the [releases page](https://github.com/pascalpp/FreeRuler/releases). The App Store version is a version behind because of an app store rejection that I'm still addressing (#76).
