### ISSUE TITLE
Measurement fonts may get clipped / truncated

### ISSUE THREAD

**Issue by aldanor** [pascalpp/FreeRuler#79]
(macOS 10.12.6)

![image](https://user-images.githubusercontent.com/2418513/71543714-2b6e1f00-296e-11ea-82a4-e8c7cc84ff4d.png)

**Comment by pascalpp** [comment]
@aldanor This should be fixed in the latest release. https://github.com/pascalpp/FreeRuler/releases

Can you download the v2.0.3 and retest?

**Comment by aldanor** [comment]
Thanks, seems to work fine! (installed from brew cask now, it seems like the app store still has 2.0.2)

**Comment by pascalpp** [comment]
Neato, didn't realize this was published on homebrew. Whoever did that, thanks!
