### ISSUE TITLE
Doesnt work on 10.11.6

### ISSUE THREAD

**Issue by schroef** [pascalpp/FreeRuler#88]
Perhaps add to the requirements it doesnt work for 10.11.6
Currently states Catalina, Mojave and perhaps older. Well 10.11.6 is not supported. Tried all versions.

**Comment by schroef** [comment]
Doest have anything coded in other parts what the min requirements are? I just noticed the Plist had 10.14 as a minimum. I know changing this sometimes works. But in this case it didnt.

**Comment by pascalpp** [comment]
Yeah unfortunately I don't have time to support older versions in Free Ruler 2. You can download the older version of Free Ruler [here](http://pascal.com/software/freeruler/index1.7.html) which should support your version of Mac OS.

**Comment by schroef** [comment]
WOw fast response pascal. Ill try that one, thanks again!
