### ISSUE TITLE
labels above 950 are truncated

### ISSUE THREAD

**Issue by pascalpp** [pascalpp/FreeRuler#9]
![image](https://user-images.githubusercontent.com/1355312/56452021-9013ad00-62fc-11e9-91f7-67957b6f32cf.png)

**Comment by jeff-h** [comment]
I believe that's because the label is being drawn only 20px wide. I guess since we're printing them every 50px, we should just make them 50px, or close to it.

https://github.com/pascalpp/FreeRuler/blob/v2-vertical-window/Free%20Ruler/HorizontalRule.swift#L57

**Comment by pascalpp** [comment]
fixed in grouping branch
